/*
 * Cartesia REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-06-10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status_code")]
pub enum TtsSsePost200Response {
    #[serde(rename="JSONChunkResponse")]
    JsonChunkResponse(Box<models::JsonChunkResponse>),
    #[serde(rename="JSONDoneResponse")]
    JsonDoneResponse(Box<models::JsonDoneResponse>),
    #[serde(rename="JSONErrorResponse")]
    JsonErrorResponse(Box<models::JsonErrorResponse>),
}

impl Default for TtsSsePost200Response {
    fn default() -> Self {
        Self::JsonChunkResponse(Default::default())
    }
}


