/*
 * Cartesia REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-06-10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoiceEmbedding {
    #[serde(rename = "embedding")]
    pub embedding: Vec<f64>,
}

impl VoiceEmbedding {
    pub fn new(embedding: Vec<f64>) -> VoiceEmbedding {
        VoiceEmbedding {
            embedding,
        }
    }
}

