/*
 * Cartesia REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-06-10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Voice1 : The voice to use for the speech. Can be either an ID or an embedding, specified by the `mode` field.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "mode")]
pub enum Voice1 {
    #[serde(rename="Voice_1_oneOf")]
    Voice1OneOf(Box<models::Voice1OneOf>),
    #[serde(rename="Voice_1_oneOf_1")]
    Voice1OneOf1(Box<models::Voice1OneOf1>),
}

impl Default for Voice1 {
    fn default() -> Self {
        Self::Voice1OneOf(Default::default())
    }
}


